// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7A_F8vRqtQJHWahbJTEJc9mNbIqZpvWY',
    appId: '1:356365705247:web:c62cc7790040c7ce1df52a',
    messagingSenderId: '356365705247',
    projectId: 'pet-project-ca87b',
    authDomain: 'pet-project-ca87b.firebaseapp.com',
    storageBucket: 'pet-project-ca87b.appspot.com',
    measurementId: 'G-3YEJ1DQ7DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOfOaP1dt-iQ2vPrXYSOMr3dZ8P5wVpSo',
    appId: '1:356365705247:android:4eb9dd4e205c94f21df52a',
    messagingSenderId: '356365705247',
    projectId: 'pet-project-ca87b',
    storageBucket: 'pet-project-ca87b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLPyU64m4iwDVvc5cgX_x_FXiE3k4Awy0',
    appId: '1:356365705247:ios:953eefa87c790dc21df52a',
    messagingSenderId: '356365705247',
    projectId: 'pet-project-ca87b',
    storageBucket: 'pet-project-ca87b.appspot.com',
    iosBundleId: 'petProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLPyU64m4iwDVvc5cgX_x_FXiE3k4Awy0',
    appId: '1:356365705247:ios:c11406c3219b39ac1df52a',
    messagingSenderId: '356365705247',
    projectId: 'pet-project-ca87b',
    storageBucket: 'pet-project-ca87b.appspot.com',
    iosBundleId: 'com.example.petProject.RunnerTests',
  );
}
